name: Checks

on:
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: clean install
        run: npm ci

      - name: format
        run: npx nx format:check

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: clean install
        run: npm ci

      - name: test
        run: npx nx run-many -t test

  typescript:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: clean install
        run: npm ci

      - name: typescript
        run: npx tsc -b
